apiVersion: v1
kind: Service
metadata:
  name: chasqui-retail
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chasqui-retail
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
